let projects_info = [{
        id: 1,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "in 3 days",
    },

    {
        id: 2,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 3,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Draft",
        next_milestone: "Complete Drafting",
    },
    {
        id: 4,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Draft",
        next_milestone: "Resume Drafting",
    },
    {
        id: 5,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Draft",
        next_milestone: "Review and Revise",
    },
    {
        id: 6,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Draft",
        next_milestone: "Resume Drafting",
    },
    {
        id: 7,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Draft",
        next_milestone: "Review and Revise",
    },
    {
        id: 8,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Draft",
        next_milestone: "complete Draft",
    },
    {
        id: 9,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Draft",
        next_milestone: "Review and Revise",
    },
    {
        id: 10,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "jan 5th",
    },
    {
        id: 11,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "Next week",
    },
    {
        id: 12,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "in 5 days",
    },
    {
        id: 13,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "in 2 weeks",
    },
    {
        id: 14,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "Feb 10th",
    },
    {
        id: 15,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "June ",
    },
    {
        id: 16,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 17,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 18,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 19,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 20,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 21,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 22,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Cancelled",
        next_milestone: "None(project cancelled)",
    },
    {
        id: 23,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Cancelled",
        next_milestone: "None(project cancelled)",
    },
    {
        id: 24,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Cancelled",
        next_milestone: "None(project cancelled)",
    },
    {
        id: 25,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Cancelled",
        next_milestone: "None(project cancelled)",
    }, {
        id: 26,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "June ",
    },
    {
        id: 27,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Ongoing",
        next_milestone: "March",
    },
    {
        id: 28,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 29,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 30,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
    {
        id: 31,
        name: "Make an E-Commerce Website For a Brand Store",
        category: "Completed",
        next_milestone: "Deployment",
    },
]

export default projects_info;